@startuml
'https://plantuml.com/class-diagram

class main{
 - operand1 : float
 - operator : char
 - operand2 : float
 - result : float

 +main():void
 -ask_user_input():void
 -calculate(float:operand1, char:operator, float:operand2):float
 -display_result(float:operand1, char:operator, float:operand2, int:result):void
 -ask_user_float_input():float
}
@enduml